name: CI
on: [push, pull_request]

#env:

jobs:
  build:
    runs-on: ubuntu-latest
    # 大约用时 20 分钟
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2

      # cache cargo
      - uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-1
      # rust 编译工具
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          #target: wasm32-unknown-unknown
          components: rustfmt, clippy
      - run: cargo --version

      # 主要编译过程 (检查, 测试, 编译)
      - run: cargo fmt --check
      - run: cargo test --all-features

      # default cargo features
      - run: cargo build --release
      # feature: api
      - run: cargo build --release --no-default-features --features api
      # feature: server
      - run: cargo build --release --no-default-features --features server
      # feature: window
      - run: cargo build --release --no-default-features --features window
      # all cargo features
      - run: cargo build --release --all-features

      # 上传编译结果
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: libvrecore.rlib
          path: target/release/libvrecore.rlib
